#!/usr/bin/python3

"""Module: Counts the number of occurrences of each nucleotide in a given strand of DNA."""

def dna_stats(dna_string):
    """
    Counts the number of occurrences of each nucleotide in a given strand of DNA.


    Args:

    dna_string: A string representing the order of nucleobases along one strand of a double-stranded DNA molecule.


    Usage:

    >>> dna_stats("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")
    20 12 17 21

    """
    nucleotideList = ['A', 'C', 'G', 'T']
    countList = []
    
    for item in nucleotideList:
        countList.append(dna_string.count(item))

    for item in countList:
        print(item, end=" ")

dna_stats("AGAAGTTGCAACGAATAGGTTTGGCCGGCGCAAGACGTCAAACATAGCCCTCTCGCAGAAGTTTGGCAAATACGTAATGTGAAAGGTGGACCAAACGACCTCGTAAAGCTTTCGGCAGGAGTCCCACAATTTGCACATCCACAGTCCACTGTACTGGTGCAGAATGGGTTTGCAGCGGCTTGGGAACGCGGAATGACACTAGGGATGATTTAGACACTACTAAGCGCTCCAGTTTGCACCCCCGGGGGGACGAGTCGCTCGCTCCCGGAGAGTAGTCCGGCAATAGATCGTTAGTCTATGTGCTCCGCACCTGTATTTTTCACTGTAGCGTTAAGATAGAGCTGAGTAAACCTCAGGTTTCGACCCTCCTCTCAGGGGAGCGAGCAGTGGGTCATTAAGTCGGGAAGCCGAGAATTGCCCTGGAAGAGTCTCGAAGATGCCACGCGAGTCAGTTCGTAGGCGTACAAGTGTAGTAAGCCCATCGTCCCGCCCTTTGGGCCCTAGCCAGGCTATCGGTTGAAGGCTAAACGCCGAGAGCTCACGAGCGCAATGAGCTATTTATCCTTAAGAACCGGTGCTCCGTTACTACAACGCCGTTTCTACAAACATAGGATGTATACCATATTATGTGCTATAGAGTCTCGTGAGTTGCTCTGGCCACAGATCGGGCTGCTTTCCACTAAGTTTACCGACCTGCGCAAACTATGGTTTGGAAGGTTGAACTGTAAAGGCCATAGCCTAGAGTTAATCATCGAAGGCTCCTCGATTACTCAGACTCAACCGCAGTCTTCTTCTCAGCCTGTATTCCGGGACCGTCTCGCAGCTT")
